/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * BotCheckResponse.h
 *
 * Result of performing a Bot check on an IP address
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_BotCheckResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_BotCheckResponse_H_


#include "../ModelBase.h"


namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Result of performing a Bot check on an IP address
/// </summary>
class  BotCheckResponse
    : public ModelBase
{
public:
    BotCheckResponse();
    virtual ~BotCheckResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BotCheckResponse members

    /// <summary>
    /// True if the input IP address is a Bot or Robot, false otherwise
    /// </summary>
    bool isIsBot() const;
    bool isBotIsSet() const;
    void unsetIsBot();
    void setIsBot(bool value);

protected:
    bool m_IsBot;
    bool m_IsBotIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_BotCheckResponse_H_ */
