/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "BotCheckResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

BotCheckResponse::BotCheckResponse()
{
    m_IsBot = false;
    m_IsBotIsSet = false;
}

BotCheckResponse::~BotCheckResponse()
{
}

void BotCheckResponse::validate()
{
    // TODO: implement validation
}

web::json::value BotCheckResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IsBotIsSet)
    {
        val[utility::conversions::to_string_t("IsBot")] = ModelBase::toJson(m_IsBot);
    }

    return val;
}

void BotCheckResponse::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("IsBot")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("IsBot")];
        if(!fieldValue.is_null())
        {
            setIsBot(ModelBase::boolFromJson(fieldValue));
        }
    }
}

void BotCheckResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_IsBotIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("IsBot"), m_IsBot));
    }
}

void BotCheckResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("IsBot")))
    {
        setIsBot(ModelBase::boolFromHttpContent(multipart->getContent(utility::conversions::to_string_t("IsBot"))));
    }
}

bool BotCheckResponse::isIsBot() const
{
    return m_IsBot;
}


void BotCheckResponse::setIsBot(bool value)
{
    m_IsBot = value;
    m_IsBotIsSet = true;
}
bool BotCheckResponse::isBotIsSet() const
{
    return m_IsBotIsSet;
}

void BotCheckResponse::unsetIsBot()
{
    m_IsBotIsSet = false;
}

}
}
}
}

