/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * CountryListResult.h
 *
 * Result of enumerating available countries
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_CountryListResult_H_
#define IO_SWAGGER_CLIENT_MODEL_CountryListResult_H_


#include "../ModelBase.h"

#include <vector>
#include "CountryDetails.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Result of enumerating available countries
/// </summary>
class  CountryListResult
    : public ModelBase
{
public:
    CountryListResult();
    virtual ~CountryListResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CountryListResult members

    /// <summary>
    /// True if the operation was successful, false otherwise
    /// </summary>
    bool isSuccessful() const;
    bool successfulIsSet() const;
    void unsetSuccessful();
    void setSuccessful(bool value);
    /// <summary>
    /// List of current ISO 3166-1 countries in the world
    /// </summary>
    std::vector<std::shared_ptr<CountryDetails>>& getCountries();
    bool countriesIsSet() const;
    void unsetCountries();
    void setCountries(std::vector<std::shared_ptr<CountryDetails>> value);

protected:
    bool m_Successful;
    bool m_SuccessfulIsSet;
    std::vector<std::shared_ptr<CountryDetails>> m_Countries;
    bool m_CountriesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_CountryListResult_H_ */
