/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "DateTimeNaturalLanguageParseRequest.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

DateTimeNaturalLanguageParseRequest::DateTimeNaturalLanguageParseRequest()
{
    m_RawDateTimeInput = utility::conversions::to_string_t("");
    m_RawDateTimeInputIsSet = false;
}

DateTimeNaturalLanguageParseRequest::~DateTimeNaturalLanguageParseRequest()
{
}

void DateTimeNaturalLanguageParseRequest::validate()
{
    // TODO: implement validation
}

web::json::value DateTimeNaturalLanguageParseRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_RawDateTimeInputIsSet)
    {
        val[utility::conversions::to_string_t("RawDateTimeInput")] = ModelBase::toJson(m_RawDateTimeInput);
    }

    return val;
}

void DateTimeNaturalLanguageParseRequest::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("RawDateTimeInput")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("RawDateTimeInput")];
        if(!fieldValue.is_null())
        {
            setRawDateTimeInput(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void DateTimeNaturalLanguageParseRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_RawDateTimeInputIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("RawDateTimeInput"), m_RawDateTimeInput));
        
    }
}

void DateTimeNaturalLanguageParseRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("RawDateTimeInput")))
    {
        setRawDateTimeInput(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("RawDateTimeInput"))));
    }
}

utility::string_t DateTimeNaturalLanguageParseRequest::getRawDateTimeInput() const
{
    return m_RawDateTimeInput;
}


void DateTimeNaturalLanguageParseRequest::setRawDateTimeInput(utility::string_t value)
{
    m_RawDateTimeInput = value;
    m_RawDateTimeInputIsSet = true;
}
bool DateTimeNaturalLanguageParseRequest::rawDateTimeInputIsSet() const
{
    return m_RawDateTimeInputIsSet;
}

void DateTimeNaturalLanguageParseRequest::unsetRawDateTimeInput()
{
    m_RawDateTimeInputIsSet = false;
}

}
}
}
}

