/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FullNameValidationRequest.h
 *
 * Request to validate a full name string
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FullNameValidationRequest_H_
#define IO_SWAGGER_CLIENT_MODEL_FullNameValidationRequest_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Request to validate a full name string
/// </summary>
class  FullNameValidationRequest
    : public ModelBase
{
public:
    FullNameValidationRequest();
    virtual ~FullNameValidationRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FullNameValidationRequest members

    /// <summary>
    /// Full name to process as a free-form string; supports many components such as First Name, Middle Name, Last Name, Title, Nickname, Suffix, and Display Name
    /// </summary>
    utility::string_t getFullNameString() const;
    bool fullNameStringIsSet() const;
    void unsetFullNameString();
    void setFullNameString(utility::string_t value);

protected:
    utility::string_t m_FullNameString;
    bool m_FullNameStringIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FullNameValidationRequest_H_ */
