/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * GeolocateStreetAddressResponse.h
 *
 * Geolocation street address result
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_GeolocateStreetAddressResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_GeolocateStreetAddressResponse_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Geolocation street address result
/// </summary>
class  GeolocateStreetAddressResponse
    : public ModelBase
{
public:
    GeolocateStreetAddressResponse();
    virtual ~GeolocateStreetAddressResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GeolocateStreetAddressResponse members

    /// <summary>
    /// Two-letter country code of IP address
    /// </summary>
    utility::string_t getCountryCode() const;
    bool countryCodeIsSet() const;
    void unsetCountryCode();
    void setCountryCode(utility::string_t value);
    /// <summary>
    /// Country name of IP address
    /// </summary>
    utility::string_t getCountryName() const;
    bool countryNameIsSet() const;
    void unsetCountryName();
    void setCountryName(utility::string_t value);
    /// <summary>
    /// Street address of IP address
    /// </summary>
    utility::string_t getStreetAddress() const;
    bool streetAddressIsSet() const;
    void unsetStreetAddress();
    void setStreetAddress(utility::string_t value);
    /// <summary>
    /// City of IP address
    /// </summary>
    utility::string_t getCity() const;
    bool cityIsSet() const;
    void unsetCity();
    void setCity(utility::string_t value);
    /// <summary>
    /// State/region of IP address
    /// </summary>
    utility::string_t getRegionName() const;
    bool regionNameIsSet() const;
    void unsetRegionName();
    void setRegionName(utility::string_t value);
    /// <summary>
    /// Zip or postal code of IP address
    /// </summary>
    utility::string_t getZipCode() const;
    bool zipCodeIsSet() const;
    void unsetZipCode();
    void setZipCode(utility::string_t value);

protected:
    utility::string_t m_CountryCode;
    bool m_CountryCodeIsSet;
    utility::string_t m_CountryName;
    bool m_CountryNameIsSet;
    utility::string_t m_StreetAddress;
    bool m_StreetAddressIsSet;
    utility::string_t m_City;
    bool m_CityIsSet;
    utility::string_t m_RegionName;
    bool m_RegionNameIsSet;
    utility::string_t m_ZipCode;
    bool m_ZipCodeIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_GeolocateStreetAddressResponse_H_ */
