/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "GetGenderResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

GetGenderResponse::GetGenderResponse()
{
    m_Successful = false;
    m_SuccessfulIsSet = false;
    m_Gender = utility::conversions::to_string_t("");
    m_GenderIsSet = false;
}

GetGenderResponse::~GetGenderResponse()
{
}

void GetGenderResponse::validate()
{
    // TODO: implement validation
}

web::json::value GetGenderResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_SuccessfulIsSet)
    {
        val[utility::conversions::to_string_t("Successful")] = ModelBase::toJson(m_Successful);
    }
    if(m_GenderIsSet)
    {
        val[utility::conversions::to_string_t("Gender")] = ModelBase::toJson(m_Gender);
    }

    return val;
}

void GetGenderResponse::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("Successful")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Successful")];
        if(!fieldValue.is_null())
        {
            setSuccessful(ModelBase::boolFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Gender")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Gender")];
        if(!fieldValue.is_null())
        {
            setGender(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void GetGenderResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_SuccessfulIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Successful"), m_Successful));
    }
    if(m_GenderIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Gender"), m_Gender));
        
    }
}

void GetGenderResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("Successful")))
    {
        setSuccessful(ModelBase::boolFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Successful"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Gender")))
    {
        setGender(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Gender"))));
    }
}

bool GetGenderResponse::isSuccessful() const
{
    return m_Successful;
}


void GetGenderResponse::setSuccessful(bool value)
{
    m_Successful = value;
    m_SuccessfulIsSet = true;
}
bool GetGenderResponse::successfulIsSet() const
{
    return m_SuccessfulIsSet;
}

void GetGenderResponse::unsetSuccessful()
{
    m_SuccessfulIsSet = false;
}

utility::string_t GetGenderResponse::getGender() const
{
    return m_Gender;
}


void GetGenderResponse::setGender(utility::string_t value)
{
    m_Gender = value;
    m_GenderIsSet = true;
}
bool GetGenderResponse::genderIsSet() const
{
    return m_GenderIsSet;
}

void GetGenderResponse::unsetGender()
{
    m_GenderIsSet = false;
}

}
}
}
}

