/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "GetPublicHolidaysRequest.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

GetPublicHolidaysRequest::GetPublicHolidaysRequest()
{
    m_RawCountryInput = utility::conversions::to_string_t("");
    m_RawCountryInputIsSet = false;
    m_Year = 0;
    m_YearIsSet = false;
}

GetPublicHolidaysRequest::~GetPublicHolidaysRequest()
{
}

void GetPublicHolidaysRequest::validate()
{
    // TODO: implement validation
}

web::json::value GetPublicHolidaysRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_RawCountryInputIsSet)
    {
        val[utility::conversions::to_string_t("RawCountryInput")] = ModelBase::toJson(m_RawCountryInput);
    }
    if(m_YearIsSet)
    {
        val[utility::conversions::to_string_t("Year")] = ModelBase::toJson(m_Year);
    }

    return val;
}

void GetPublicHolidaysRequest::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("RawCountryInput")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("RawCountryInput")];
        if(!fieldValue.is_null())
        {
            setRawCountryInput(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Year")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Year")];
        if(!fieldValue.is_null())
        {
            setYear(ModelBase::int32_tFromJson(fieldValue));
        }
    }
}

void GetPublicHolidaysRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_RawCountryInputIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("RawCountryInput"), m_RawCountryInput));
        
    }
    if(m_YearIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Year"), m_Year));
    }
}

void GetPublicHolidaysRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("RawCountryInput")))
    {
        setRawCountryInput(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("RawCountryInput"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Year")))
    {
        setYear(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Year"))));
    }
}

utility::string_t GetPublicHolidaysRequest::getRawCountryInput() const
{
    return m_RawCountryInput;
}


void GetPublicHolidaysRequest::setRawCountryInput(utility::string_t value)
{
    m_RawCountryInput = value;
    m_RawCountryInputIsSet = true;
}
bool GetPublicHolidaysRequest::rawCountryInputIsSet() const
{
    return m_RawCountryInputIsSet;
}

void GetPublicHolidaysRequest::unsetRawCountryInput()
{
    m_RawCountryInputIsSet = false;
}

int32_t GetPublicHolidaysRequest::getYear() const
{
    return m_Year;
}


void GetPublicHolidaysRequest::setYear(int32_t value)
{
    m_Year = value;
    m_YearIsSet = true;
}
bool GetPublicHolidaysRequest::yearIsSet() const
{
    return m_YearIsSet;
}

void GetPublicHolidaysRequest::unsetYear()
{
    m_YearIsSet = false;
}

}
}
}
}

