/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.10.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "GetTimezonesRequest.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

GetTimezonesRequest::GetTimezonesRequest()
{
    m_CountryCodeOrName = utility::conversions::to_string_t("");
    m_CountryCodeOrNameIsSet = false;
}

GetTimezonesRequest::~GetTimezonesRequest()
{
}

void GetTimezonesRequest::validate()
{
    // TODO: implement validation
}

web::json::value GetTimezonesRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_CountryCodeOrNameIsSet)
    {
        val[utility::conversions::to_string_t("CountryCodeOrName")] = ModelBase::toJson(m_CountryCodeOrName);
    }

    return val;
}

void GetTimezonesRequest::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("CountryCodeOrName")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("CountryCodeOrName")];
        if(!fieldValue.is_null())
        {
            setCountryCodeOrName(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void GetTimezonesRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_CountryCodeOrNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("CountryCodeOrName"), m_CountryCodeOrName));
        
    }
}

void GetTimezonesRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("CountryCodeOrName")))
    {
        setCountryCodeOrName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("CountryCodeOrName"))));
    }
}

utility::string_t GetTimezonesRequest::getCountryCodeOrName() const
{
    return m_CountryCodeOrName;
}


void GetTimezonesRequest::setCountryCodeOrName(utility::string_t value)
{
    m_CountryCodeOrName = value;
    m_CountryCodeOrNameIsSet = true;
}
bool GetTimezonesRequest::countryCodeOrNameIsSet() const
{
    return m_CountryCodeOrNameIsSet;
}

void GetTimezonesRequest::unsetCountryCodeOrName()
{
    m_CountryCodeOrNameIsSet = false;
}

}
}
}
}

