/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "IPReverseDNSLookupResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

IPReverseDNSLookupResponse::IPReverseDNSLookupResponse()
{
    m_Successful = false;
    m_SuccessfulIsSet = false;
    m_HostName = utility::conversions::to_string_t("");
    m_HostNameIsSet = false;
}

IPReverseDNSLookupResponse::~IPReverseDNSLookupResponse()
{
}

void IPReverseDNSLookupResponse::validate()
{
    // TODO: implement validation
}

web::json::value IPReverseDNSLookupResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_SuccessfulIsSet)
    {
        val[utility::conversions::to_string_t("Successful")] = ModelBase::toJson(m_Successful);
    }
    if(m_HostNameIsSet)
    {
        val[utility::conversions::to_string_t("HostName")] = ModelBase::toJson(m_HostName);
    }

    return val;
}

void IPReverseDNSLookupResponse::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("Successful")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Successful")];
        if(!fieldValue.is_null())
        {
            setSuccessful(ModelBase::boolFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("HostName")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("HostName")];
        if(!fieldValue.is_null())
        {
            setHostName(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void IPReverseDNSLookupResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_SuccessfulIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Successful"), m_Successful));
    }
    if(m_HostNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("HostName"), m_HostName));
        
    }
}

void IPReverseDNSLookupResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("Successful")))
    {
        setSuccessful(ModelBase::boolFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Successful"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("HostName")))
    {
        setHostName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("HostName"))));
    }
}

bool IPReverseDNSLookupResponse::isSuccessful() const
{
    return m_Successful;
}


void IPReverseDNSLookupResponse::setSuccessful(bool value)
{
    m_Successful = value;
    m_SuccessfulIsSet = true;
}
bool IPReverseDNSLookupResponse::successfulIsSet() const
{
    return m_SuccessfulIsSet;
}

void IPReverseDNSLookupResponse::unsetSuccessful()
{
    m_SuccessfulIsSet = false;
}

utility::string_t IPReverseDNSLookupResponse::getHostName() const
{
    return m_HostName;
}


void IPReverseDNSLookupResponse::setHostName(utility::string_t value)
{
    m_HostName = value;
    m_HostNameIsSet = true;
}
bool IPReverseDNSLookupResponse::hostNameIsSet() const
{
    return m_HostNameIsSet;
}

void IPReverseDNSLookupResponse::unsetHostName()
{
    m_HostNameIsSet = false;
}

}
}
}
}

