/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IPThreatResponse.h
 *
 * Result of performing a IP threat check on an IP address
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_IPThreatResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_IPThreatResponse_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Result of performing a IP threat check on an IP address
/// </summary>
class  IPThreatResponse
    : public ModelBase
{
public:
    IPThreatResponse();
    virtual ~IPThreatResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IPThreatResponse members

    /// <summary>
    /// True if the input IP address is a threat, false otherwise
    /// </summary>
    bool isIsThreat() const;
    bool isThreatIsSet() const;
    void unsetIsThreat();
    void setIsThreat(bool value);
    /// <summary>
    /// Specifies the type of IP threat; possible values include Blocklist, Botnet, WebBot
    /// </summary>
    utility::string_t getThreatType() const;
    bool threatTypeIsSet() const;
    void unsetThreatType();
    void setThreatType(utility::string_t value);

protected:
    bool m_IsThreat;
    bool m_IsThreatIsSet;
    utility::string_t m_ThreatType;
    bool m_ThreatTypeIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_IPThreatResponse_H_ */
