/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "IPThreatResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

IPThreatResponse::IPThreatResponse()
{
    m_IsThreat = false;
    m_IsThreatIsSet = false;
    m_ThreatType = utility::conversions::to_string_t("");
    m_ThreatTypeIsSet = false;
}

IPThreatResponse::~IPThreatResponse()
{
}

void IPThreatResponse::validate()
{
    // TODO: implement validation
}

web::json::value IPThreatResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IsThreatIsSet)
    {
        val[utility::conversions::to_string_t("IsThreat")] = ModelBase::toJson(m_IsThreat);
    }
    if(m_ThreatTypeIsSet)
    {
        val[utility::conversions::to_string_t("ThreatType")] = ModelBase::toJson(m_ThreatType);
    }

    return val;
}

void IPThreatResponse::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("IsThreat")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("IsThreat")];
        if(!fieldValue.is_null())
        {
            setIsThreat(ModelBase::boolFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("ThreatType")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("ThreatType")];
        if(!fieldValue.is_null())
        {
            setThreatType(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void IPThreatResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_IsThreatIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("IsThreat"), m_IsThreat));
    }
    if(m_ThreatTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("ThreatType"), m_ThreatType));
        
    }
}

void IPThreatResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("IsThreat")))
    {
        setIsThreat(ModelBase::boolFromHttpContent(multipart->getContent(utility::conversions::to_string_t("IsThreat"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("ThreatType")))
    {
        setThreatType(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("ThreatType"))));
    }
}

bool IPThreatResponse::isIsThreat() const
{
    return m_IsThreat;
}


void IPThreatResponse::setIsThreat(bool value)
{
    m_IsThreat = value;
    m_IsThreatIsSet = true;
}
bool IPThreatResponse::isThreatIsSet() const
{
    return m_IsThreatIsSet;
}

void IPThreatResponse::unsetIsThreat()
{
    m_IsThreatIsSet = false;
}

utility::string_t IPThreatResponse::getThreatType() const
{
    return m_ThreatType;
}


void IPThreatResponse::setThreatType(utility::string_t value)
{
    m_ThreatType = value;
    m_ThreatTypeIsSet = true;
}
bool IPThreatResponse::threatTypeIsSet() const
{
    return m_ThreatTypeIsSet;
}

void IPThreatResponse::unsetThreatType()
{
    m_ThreatTypeIsSet = false;
}

}
}
}
}

