/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.10.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "LastNameValidationRequest.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

LastNameValidationRequest::LastNameValidationRequest()
{
    m_LastName = utility::conversions::to_string_t("");
    m_LastNameIsSet = false;
}

LastNameValidationRequest::~LastNameValidationRequest()
{
}

void LastNameValidationRequest::validate()
{
    // TODO: implement validation
}

web::json::value LastNameValidationRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_LastNameIsSet)
    {
        val[utility::conversions::to_string_t("LastName")] = ModelBase::toJson(m_LastName);
    }

    return val;
}

void LastNameValidationRequest::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("LastName")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("LastName")];
        if(!fieldValue.is_null())
        {
            setLastName(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void LastNameValidationRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_LastNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("LastName"), m_LastName));
        
    }
}

void LastNameValidationRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("LastName")))
    {
        setLastName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("LastName"))));
    }
}

utility::string_t LastNameValidationRequest::getLastName() const
{
    return m_LastName;
}


void LastNameValidationRequest::setLastName(utility::string_t value)
{
    m_LastName = value;
    m_LastNameIsSet = true;
}
bool LastNameValidationRequest::lastNameIsSet() const
{
    return m_LastNameIsSet;
}

void LastNameValidationRequest::unsetLastName()
{
    m_LastNameIsSet = false;
}

}
}
}
}

