/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.5.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "LastNameValidationResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

LastNameValidationResponse::LastNameValidationResponse()
{
    m_Successful = false;
    m_SuccessfulIsSet = false;
    m_ValidationResult = utility::conversions::to_string_t("");
    m_ValidationResultIsSet = false;
}

LastNameValidationResponse::~LastNameValidationResponse()
{
}

void LastNameValidationResponse::validate()
{
    // TODO: implement validation
}

web::json::value LastNameValidationResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_SuccessfulIsSet)
    {
        val[utility::conversions::to_string_t("Successful")] = ModelBase::toJson(m_Successful);
    }
    if(m_ValidationResultIsSet)
    {
        val[utility::conversions::to_string_t("ValidationResult")] = ModelBase::toJson(m_ValidationResult);
    }

    return val;
}

void LastNameValidationResponse::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("Successful")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Successful")];
        if(!fieldValue.is_null())
        {
            setSuccessful(ModelBase::boolFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("ValidationResult")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("ValidationResult")];
        if(!fieldValue.is_null())
        {
            setValidationResult(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void LastNameValidationResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_SuccessfulIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Successful"), m_Successful));
    }
    if(m_ValidationResultIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("ValidationResult"), m_ValidationResult));
        
    }
}

void LastNameValidationResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("Successful")))
    {
        setSuccessful(ModelBase::boolFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Successful"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("ValidationResult")))
    {
        setValidationResult(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("ValidationResult"))));
    }
}

bool LastNameValidationResponse::isSuccessful() const
{
    return m_Successful;
}


void LastNameValidationResponse::setSuccessful(bool value)
{
    m_Successful = value;
    m_SuccessfulIsSet = true;
}
bool LastNameValidationResponse::successfulIsSet() const
{
    return m_SuccessfulIsSet;
}

void LastNameValidationResponse::unsetSuccessful()
{
    m_SuccessfulIsSet = false;
}

utility::string_t LastNameValidationResponse::getValidationResult() const
{
    return m_ValidationResult;
}


void LastNameValidationResponse::setValidationResult(utility::string_t value)
{
    m_ValidationResult = value;
    m_ValidationResultIsSet = true;
}
bool LastNameValidationResponse::validationResultIsSet() const
{
    return m_ValidationResultIsSet;
}

void LastNameValidationResponse::unsetValidationResult()
{
    m_ValidationResultIsSet = false;
}

}
}
}
}

