/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.5.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "ParseAddressRequest.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

ParseAddressRequest::ParseAddressRequest()
{
    m_AddressString = utility::conversions::to_string_t("");
    m_AddressStringIsSet = false;
    m_CapitalizationMode = utility::conversions::to_string_t("");
    m_CapitalizationModeIsSet = false;
}

ParseAddressRequest::~ParseAddressRequest()
{
}

void ParseAddressRequest::validate()
{
    // TODO: implement validation
}

web::json::value ParseAddressRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_AddressStringIsSet)
    {
        val[utility::conversions::to_string_t("AddressString")] = ModelBase::toJson(m_AddressString);
    }
    if(m_CapitalizationModeIsSet)
    {
        val[utility::conversions::to_string_t("CapitalizationMode")] = ModelBase::toJson(m_CapitalizationMode);
    }

    return val;
}

void ParseAddressRequest::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("AddressString")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("AddressString")];
        if(!fieldValue.is_null())
        {
            setAddressString(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("CapitalizationMode")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("CapitalizationMode")];
        if(!fieldValue.is_null())
        {
            setCapitalizationMode(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void ParseAddressRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_AddressStringIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("AddressString"), m_AddressString));
        
    }
    if(m_CapitalizationModeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("CapitalizationMode"), m_CapitalizationMode));
        
    }
}

void ParseAddressRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("AddressString")))
    {
        setAddressString(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("AddressString"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("CapitalizationMode")))
    {
        setCapitalizationMode(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("CapitalizationMode"))));
    }
}

utility::string_t ParseAddressRequest::getAddressString() const
{
    return m_AddressString;
}


void ParseAddressRequest::setAddressString(utility::string_t value)
{
    m_AddressString = value;
    m_AddressStringIsSet = true;
}
bool ParseAddressRequest::addressStringIsSet() const
{
    return m_AddressStringIsSet;
}

void ParseAddressRequest::unsetAddressString()
{
    m_AddressStringIsSet = false;
}

utility::string_t ParseAddressRequest::getCapitalizationMode() const
{
    return m_CapitalizationMode;
}


void ParseAddressRequest::setCapitalizationMode(utility::string_t value)
{
    m_CapitalizationMode = value;
    m_CapitalizationModeIsSet = true;
}
bool ParseAddressRequest::capitalizationModeIsSet() const
{
    return m_CapitalizationModeIsSet;
}

void ParseAddressRequest::unsetCapitalizationMode()
{
    m_CapitalizationModeIsSet = false;
}

}
}
}
}

