/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.10.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "PhoneNumberValidateRequest.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

PhoneNumberValidateRequest::PhoneNumberValidateRequest()
{
    m_PhoneNumber = utility::conversions::to_string_t("");
    m_PhoneNumberIsSet = false;
    m_DefaultCountryCode = utility::conversions::to_string_t("");
    m_DefaultCountryCodeIsSet = false;
}

PhoneNumberValidateRequest::~PhoneNumberValidateRequest()
{
}

void PhoneNumberValidateRequest::validate()
{
    // TODO: implement validation
}

web::json::value PhoneNumberValidateRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_PhoneNumberIsSet)
    {
        val[utility::conversions::to_string_t("PhoneNumber")] = ModelBase::toJson(m_PhoneNumber);
    }
    if(m_DefaultCountryCodeIsSet)
    {
        val[utility::conversions::to_string_t("DefaultCountryCode")] = ModelBase::toJson(m_DefaultCountryCode);
    }

    return val;
}

void PhoneNumberValidateRequest::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("PhoneNumber")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("PhoneNumber")];
        if(!fieldValue.is_null())
        {
            setPhoneNumber(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("DefaultCountryCode")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("DefaultCountryCode")];
        if(!fieldValue.is_null())
        {
            setDefaultCountryCode(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void PhoneNumberValidateRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_PhoneNumberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("PhoneNumber"), m_PhoneNumber));
        
    }
    if(m_DefaultCountryCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("DefaultCountryCode"), m_DefaultCountryCode));
        
    }
}

void PhoneNumberValidateRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("PhoneNumber")))
    {
        setPhoneNumber(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("PhoneNumber"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("DefaultCountryCode")))
    {
        setDefaultCountryCode(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("DefaultCountryCode"))));
    }
}

utility::string_t PhoneNumberValidateRequest::getPhoneNumber() const
{
    return m_PhoneNumber;
}


void PhoneNumberValidateRequest::setPhoneNumber(utility::string_t value)
{
    m_PhoneNumber = value;
    m_PhoneNumberIsSet = true;
}
bool PhoneNumberValidateRequest::phoneNumberIsSet() const
{
    return m_PhoneNumberIsSet;
}

void PhoneNumberValidateRequest::unsetPhoneNumber()
{
    m_PhoneNumberIsSet = false;
}

utility::string_t PhoneNumberValidateRequest::getDefaultCountryCode() const
{
    return m_DefaultCountryCode;
}


void PhoneNumberValidateRequest::setDefaultCountryCode(utility::string_t value)
{
    m_DefaultCountryCode = value;
    m_DefaultCountryCodeIsSet = true;
}
bool PhoneNumberValidateRequest::defaultCountryCodeIsSet() const
{
    return m_DefaultCountryCodeIsSet;
}

void PhoneNumberValidateRequest::unsetDefaultCountryCode()
{
    m_DefaultCountryCodeIsSet = false;
}

}
}
}
}

