/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SqlInjectionDetectionResult.h
 *
 * Result of performing an SQL Injection protection operation
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_SqlInjectionDetectionResult_H_
#define IO_SWAGGER_CLIENT_MODEL_SqlInjectionDetectionResult_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Result of performing an SQL Injection protection operation
/// </summary>
class  SqlInjectionDetectionResult
    : public ModelBase
{
public:
    SqlInjectionDetectionResult();
    virtual ~SqlInjectionDetectionResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SqlInjectionDetectionResult members

    /// <summary>
    /// True if the operation was successful, false otherwise
    /// </summary>
    bool isSuccessful() const;
    bool successfulIsSet() const;
    void unsetSuccessful();
    void setSuccessful(bool value);
    /// <summary>
    /// True if the input contained SQL Injection attacks, false otherwise
    /// </summary>
    bool isContainedSqlInjectionAttack() const;
    bool containedSqlInjectionAttackIsSet() const;
    void unsetContainedSqlInjectionAttack();
    void setContainedSqlInjectionAttack(bool value);
    /// <summary>
    /// Original input string
    /// </summary>
    utility::string_t getOriginalInput() const;
    bool originalInputIsSet() const;
    void unsetOriginalInput();
    void setOriginalInput(utility::string_t value);

protected:
    bool m_Successful;
    bool m_SuccessfulIsSet;
    bool m_ContainedSqlInjectionAttack;
    bool m_ContainedSqlInjectionAttackIsSet;
    utility::string_t m_OriginalInput;
    bool m_OriginalInputIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_SqlInjectionDetectionResult_H_ */
