/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UrlSsrfRequestFull.h
 *
 * Request to determine if a URL is an SSRF threat check
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_UrlSsrfRequestFull_H_
#define IO_SWAGGER_CLIENT_MODEL_UrlSsrfRequestFull_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Request to determine if a URL is an SSRF threat check
/// </summary>
class  UrlSsrfRequestFull
    : public ModelBase
{
public:
    UrlSsrfRequestFull();
    virtual ~UrlSsrfRequestFull();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UrlSsrfRequestFull members

    /// <summary>
    /// URL to validate
    /// </summary>
    utility::string_t getURL() const;
    bool uRLIsSet() const;
    void unsetURL();
    void setURL(utility::string_t value);
    /// <summary>
    /// Top level domains that you do not want to allow access to, e.g. mydomain.com - will block all subdomains as well
    /// </summary>
    std::vector<utility::string_t>& getBlockedDomains();
    bool blockedDomainsIsSet() const;
    void unsetBlockedDomains();
    void setBlockedDomains(std::vector<utility::string_t> value);

protected:
    utility::string_t m_URL;
    bool m_URLIsSet;
    std::vector<utility::string_t> m_BlockedDomains;
    bool m_BlockedDomainsIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_UrlSsrfRequestFull_H_ */
