/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UrlSsrfRequestBatch.h
 *
 * Batch operation to perform SSRF threat checks on multiple URLs
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_UrlSsrfRequestBatch_H_
#define IO_SWAGGER_CLIENT_MODEL_UrlSsrfRequestBatch_H_


#include "../ModelBase.h"

#include "UrlSsrfRequestFull.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Batch operation to perform SSRF threat checks on multiple URLs
/// </summary>
class  UrlSsrfRequestBatch
    : public ModelBase
{
public:
    UrlSsrfRequestBatch();
    virtual ~UrlSsrfRequestBatch();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UrlSsrfRequestBatch members

    /// <summary>
    /// Input URLs to check for SSRF threats
    /// </summary>
    std::vector<std::shared_ptr<UrlSsrfRequestFull>>& getInputItems();
    bool inputItemsIsSet() const;
    void unsetInputItems();
    void setInputItems(std::vector<std::shared_ptr<UrlSsrfRequestFull>> value);

protected:
    std::vector<std::shared_ptr<UrlSsrfRequestFull>> m_InputItems;
    bool m_InputItemsIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_UrlSsrfRequestBatch_H_ */
