/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "UrlSsrfRequestBatch.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

UrlSsrfRequestBatch::UrlSsrfRequestBatch()
{
    m_InputItemsIsSet = false;
}

UrlSsrfRequestBatch::~UrlSsrfRequestBatch()
{
}

void UrlSsrfRequestBatch::validate()
{
    // TODO: implement validation
}

web::json::value UrlSsrfRequestBatch::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_InputItems )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("InputItems")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void UrlSsrfRequestBatch::fromJson(web::json::value& val)
{
    {
        m_InputItems.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("InputItems")))
        {
        for( auto& item : val[utility::conversions::to_string_t("InputItems")].as_array() )
        {
            if(item.is_null())
            {
                m_InputItems.push_back( std::shared_ptr<UrlSsrfRequestFull>(nullptr) );
            }
            else
            {
                std::shared_ptr<UrlSsrfRequestFull> newItem(new UrlSsrfRequestFull());
                newItem->fromJson(item);
                m_InputItems.push_back( newItem );
            }
        }
        }
    }
}

void UrlSsrfRequestBatch::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_InputItems )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("InputItems"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void UrlSsrfRequestBatch::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        m_InputItems.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("InputItems")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("InputItems"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_InputItems.push_back( std::shared_ptr<UrlSsrfRequestFull>(nullptr) );
            }
            else
            {
                std::shared_ptr<UrlSsrfRequestFull> newItem(new UrlSsrfRequestFull());
                newItem->fromJson(item);
                m_InputItems.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<UrlSsrfRequestFull>>& UrlSsrfRequestBatch::getInputItems()
{
    return m_InputItems;
}

void UrlSsrfRequestBatch::setInputItems(std::vector<std::shared_ptr<UrlSsrfRequestFull>> value)
{
    m_InputItems = value;
    m_InputItemsIsSet = true;
}
bool UrlSsrfRequestBatch::inputItemsIsSet() const
{
    return m_InputItemsIsSet;
}

void UrlSsrfRequestBatch::unsetInputItems()
{
    m_InputItemsIsSet = false;
}

}
}
}
}

