/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "ValidateIdentifierResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

ValidateIdentifierResponse::ValidateIdentifierResponse()
{
    m_ValidIdentifier = false;
    m_ValidIdentifierIsSet = false;
    m_Error = utility::conversions::to_string_t("");
    m_ErrorIsSet = false;
}

ValidateIdentifierResponse::~ValidateIdentifierResponse()
{
}

void ValidateIdentifierResponse::validate()
{
    // TODO: implement validation
}

web::json::value ValidateIdentifierResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_ValidIdentifierIsSet)
    {
        val[utility::conversions::to_string_t("ValidIdentifier")] = ModelBase::toJson(m_ValidIdentifier);
    }
    if(m_ErrorIsSet)
    {
        val[utility::conversions::to_string_t("Error")] = ModelBase::toJson(m_Error);
    }

    return val;
}

void ValidateIdentifierResponse::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("ValidIdentifier")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("ValidIdentifier")];
        if(!fieldValue.is_null())
        {
            setValidIdentifier(ModelBase::boolFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("Error")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("Error")];
        if(!fieldValue.is_null())
        {
            setError(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void ValidateIdentifierResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_ValidIdentifierIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("ValidIdentifier"), m_ValidIdentifier));
    }
    if(m_ErrorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("Error"), m_Error));
        
    }
}

void ValidateIdentifierResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("ValidIdentifier")))
    {
        setValidIdentifier(ModelBase::boolFromHttpContent(multipart->getContent(utility::conversions::to_string_t("ValidIdentifier"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("Error")))
    {
        setError(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("Error"))));
    }
}

bool ValidateIdentifierResponse::isValidIdentifier() const
{
    return m_ValidIdentifier;
}


void ValidateIdentifierResponse::setValidIdentifier(bool value)
{
    m_ValidIdentifier = value;
    m_ValidIdentifierIsSet = true;
}
bool ValidateIdentifierResponse::validIdentifierIsSet() const
{
    return m_ValidIdentifierIsSet;
}

void ValidateIdentifierResponse::unsetValidIdentifier()
{
    m_ValidIdentifierIsSet = false;
}

utility::string_t ValidateIdentifierResponse::getError() const
{
    return m_Error;
}


void ValidateIdentifierResponse::setError(utility::string_t value)
{
    m_Error = value;
    m_ErrorIsSet = true;
}
bool ValidateIdentifierResponse::errorIsSet() const
{
    return m_ErrorIsSet;
}

void ValidateIdentifierResponse::unsetError()
{
    m_ErrorIsSet = false;
}

}
}
}
}

