/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * XssProtectionBatchResponse.h
 *
 * Result of performing a batch XSS protection operation
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_XssProtectionBatchResponse_H_
#define IO_SWAGGER_CLIENT_MODEL_XssProtectionBatchResponse_H_


#include "../ModelBase.h"

#include <vector>
#include "XssProtectionResult.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Result of performing a batch XSS protection operation
/// </summary>
class  XssProtectionBatchResponse
    : public ModelBase
{
public:
    XssProtectionBatchResponse();
    virtual ~XssProtectionBatchResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// XssProtectionBatchResponse members

    /// <summary>
    /// Results from performing a batch XSS protection operation
    /// </summary>
    std::vector<std::shared_ptr<XssProtectionResult>>& getResultItems();
    bool resultItemsIsSet() const;
    void unsetResultItems();
    void setResultItems(std::vector<std::shared_ptr<XssProtectionResult>> value);

protected:
    std::vector<std::shared_ptr<XssProtectionResult>> m_ResultItems;
    bool m_ResultItemsIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_XssProtectionBatchResponse_H_ */
