/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "XxeDetectionBatchResponse.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

XxeDetectionBatchResponse::XxeDetectionBatchResponse()
{
    m_ResultItemsIsSet = false;
}

XxeDetectionBatchResponse::~XxeDetectionBatchResponse()
{
}

void XxeDetectionBatchResponse::validate()
{
    // TODO: implement validation
}

web::json::value XxeDetectionBatchResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_ResultItems )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("ResultItems")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void XxeDetectionBatchResponse::fromJson(web::json::value& val)
{
    {
        m_ResultItems.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("ResultItems")))
        {
        for( auto& item : val[utility::conversions::to_string_t("ResultItems")].as_array() )
        {
            if(item.is_null())
            {
                m_ResultItems.push_back( std::shared_ptr<XxeDetectionResult>(nullptr) );
            }
            else
            {
                std::shared_ptr<XxeDetectionResult> newItem(new XxeDetectionResult());
                newItem->fromJson(item);
                m_ResultItems.push_back( newItem );
            }
        }
        }
    }
}

void XxeDetectionBatchResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_ResultItems )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("ResultItems"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void XxeDetectionBatchResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        m_ResultItems.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("ResultItems")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("ResultItems"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_ResultItems.push_back( std::shared_ptr<XxeDetectionResult>(nullptr) );
            }
            else
            {
                std::shared_ptr<XxeDetectionResult> newItem(new XxeDetectionResult());
                newItem->fromJson(item);
                m_ResultItems.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<XxeDetectionResult>>& XxeDetectionBatchResponse::getResultItems()
{
    return m_ResultItems;
}

void XxeDetectionBatchResponse::setResultItems(std::vector<std::shared_ptr<XxeDetectionResult>> value)
{
    m_ResultItems = value;
    m_ResultItemsIsSet = true;
}
bool XxeDetectionBatchResponse::resultItemsIsSet() const
{
    return m_ResultItemsIsSet;
}

void XxeDetectionBatchResponse::unsetResultItems()
{
    m_ResultItemsIsSet = false;
}

}
}
}
}

