/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.11.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * VatApi.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_API_VatApi_H_
#define IO_SWAGGER_CLIENT_API_VatApi_H_


#include "../ApiClient.h"

#include "VatLookupRequest.h"
#include "VatLookupResponse.h"

#include <boost/optional.hpp>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  VatApi
{
public:
    VatApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~VatApi();
    /// <summary>
    /// Validate a VAT number
    /// </summary>
    /// <remarks>
    /// Checks if a VAT code is valid, and if it is, returns more information about it.  The first two letters of the VAT number must be letters that indicate the country, such as LU20260743.  Possible country codes include Austria (AT), Belgium (BE), Bulgaria (BG), Cyprus (CY), Czech Republic (CZ), Germany (DE), Denmark (DK), Estonia (EE), Greece (EL), Spain (ES), Finland (FI), France (FR), United Kingdom (GB), Croatia (HR), Hungary (HU), Ireland (IE), Italy (IT), Lithuania (LT), Luxembourg (LU), Latvia (LV), Malta (MT), The Netherlands (NL), Poland (PL), Portugal (PT), Romania (RO), Sweden (SE), Slovenia (SI), Slovakia (SK).
    /// </remarks>
    /// <param name="input">Input VAT code</param>
    pplx::task<std::shared_ptr<VatLookupResponse>> vatVatLookup(
        std::shared_ptr<VatLookupRequest> input
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_API_VatApi_H_ */

